#/*
# * SPDX-License-Identifier: MIT
# */
#---------------------------------------------------------------------
#
FROM ubuntu:noble AS nfName-cppcheck

RUN apt-get update && \
    apt-get upgrade -y && \
    apt-get install --yes cppcheck

WORKDIR /home
COPY . .

RUN cppcheck --version && \
    cppcheck --enable=warning --force \
      --xml --xml-version=2 \
      --suppressions-list=ci-scripts/cppcheck_suppressions.list src \
      -j`nproc` \
      2> cppcheck.xml \
      1> cppcheck_build.log
